// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetDragEnabled(arg1) {
  return window['go']['main']['App']['SetDragEnabled'](arg1);
}

export function SetDragEnd() {
  return window['go']['main']['App']['SetDragEnd']();
}

export function SetDragStart() {
  return window['go']['main']['App']['SetDragStart']();
}

export function ToggleDragEnabled() {
  return window['go']['main']['App']['ToggleDragEnabled']();
}
