// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetDragEnabled(arg1:boolean):Promise<void>;

export function SetDragEnd():Promise<void>;

export function SetDragStart():Promise<void>;

export function ToggleDragEnabled():Promise<void>;
