// @ts-check
// This file is automatically generated. DO NOT EDIT

export function SetDragEnd() {
  return window['go']['main']['App']['SetDragEnd']();
}

export function SetDragStart() {
  return window['go']['main']['App']['SetDragStart']();
}
