// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPetSettings() {
  return window['go']['main']['App']['GetPetSettings']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SetDragEnd() {
  return window['go']['main']['App']['SetDragEnd']();
}

export function SetDragStart() {
  return window['go']['main']['App']['SetDragStart']();
}

export function SetScalePercent(arg1) {
  return window['go']['main']['App']['SetScalePercent'](arg1);
}

export function SetStepSize(arg1) {
  return window['go']['main']['App']['SetStepSize'](arg1);
}

export function SetVisible(arg1) {
  return window['go']['main']['App']['SetVisible'](arg1);
}

export function SetWalkIntervalMs(arg1) {
  return window['go']['main']['App']['SetWalkIntervalMs'](arg1);
}
