// This file is automatically generated. DO NOT EDIT

export function GetPetSettings():Promise<{[key: string]: number}>;

export function SetDragEnd():Promise<void>;

export function SetDragStart():Promise<void>;
